package app

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func runScriptPath(t *testing.T) string {
	t.Helper()
	_, source, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(source), "..", "..", "run.sh"))
}

func TestRunScriptUsesDirectTempOutputAndTracksThisRun(t *testing.T) {
	script := runScriptPath(t)
	if output, err := exec.Command("sh", "-n", script).CombinedOutput(); err != nil {
		t.Fatalf("sh -n run.sh: %v\n%s", err, output)
	}

	contents, err := os.ReadFile(script)
	if err != nil {
		t.Fatalf("read run.sh: %v", err)
	}
	text := string(contents)
	if strings.Contains(text, `mktemp -d "${TMPDIR:-/tmp}/ecs-reports.`) {
		t.Fatal("run.sh must not create a separate default report directory")
	}
	for _, required := range []string{
		`REPORT_DIR="${TMPDIR:-/tmp}"`,
		`comm -13 "$REPORT_BEFORE" "$REPORT_AFTER"`,
		`--output "$REPORT_DIR" --name "$REPORT_NAME"`,
		`no report generated by this run`,
		`run.sh --submit`,
		`Provider and region are auto-detected from safe local report metadata when available; --provider/--region override them, otherwise they remain blank.`,
		`有安全的本机报告元数据时会自动识别云厂商和地区；--provider/--region 可显式覆盖，无法识别时留空。`,
		`SUBMIT_PROVIDER`,
		`SUBMIT_REGION`,
		`SUBMIT_REPORT_DIR="$WORK/report"`,
		`--format json --output "$SUBMIT_REPORT_DIR"`,
		`submit --input "$SUBMIT_REPORT" --output "$SUBMIT_OUTPUT"`,
		`reject_submit_value`,
		`--provider 不能重复`,
		`--region 不能重复`,
		`--output 不能重复`,
		`ECS_PLAN_FILE=`,
		`submit --help >/dev/null 2>&1`,
		`--reveal is not allowed in submit mode`,
		`validate_submit_parent`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh missing report-output guard %q", required)
		}
	}
	if strings.Contains(text, `"${WORK}/ecs" "$@" --submit`) {
		t.Fatal("run.sh must strip --submit before invoking ecs run")
	}
	if strings.Contains(text, `--submit --profile full --yes --provider vultr --region jp-tokyo`) {
		t.Fatal("run.sh canonical submit example must not require provider or region")
	}
	reportPathsStart := strings.Index(text, "\nreport_paths() {")
	if reportPathsStart < 0 {
		t.Fatal("run.sh report_paths function is missing")
	}
	reportPathsEnd := strings.Index(text[reportPathsStart:], "\n}\n\n# 不使用 exec")
	if reportPathsEnd < 0 {
		t.Fatal("run.sh report_paths function is incomplete")
	}
	if strings.Contains(text[reportPathsStart:reportPathsStart+reportPathsEnd], `"$REPORT_DIR"/*.json`) {
		t.Fatal("run.sh must not select an arbitrary JSON from the report directory")
	}
}

func TestRunScriptDocumentsProfileMembership(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		"The standard profile includes cnspeed and omits multi-source IP quality and Ookla; the full profile adds both omitted modules.",
		"standard 默认包含 cnspeed，不包含多源 IP 质量与 Ookla；full 增加后两项。",
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh help is missing profile membership policy %q", required)
		}
	}
	for _, forbidden := range []string{
		"The standard and full profiles omit Ookla by default",
		"standard 和 full 默认不包含 Ookla",
	} {
		if strings.Contains(text, forbidden) {
			t.Fatalf("run.sh retains stale Ookla profile wording %q", forbidden)
		}
	}
}

func TestRunScriptPreparesStandaloneCorpusOnlyForZstd(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		"ZSTD_CORPUS_ASSET='ecs-corpus_silesia-v1.tar.gz'",
		"ZSTD_CORPUS_BYTES=211938580",
		"prepare_zstd_corpus()",
		"tar -tzf \"$ZSTD_CORPUS_ARCHIVE\"",
		"tar -xzf \"$ZSTD_CORPUS_ARCHIVE\" -C \"$ZSTD_CORPUS_EXTRACT_ROOT\" \"$ZSTD_CORPUS_NAME\"",
		"[ \"$(stat -c %s \"$zstd_corpus_path\")\" -eq \"$ZSTD_CORPUS_BYTES\" ]",
		"export ECS_ZSTD_CORPUS=\"$zstd_corpus_path\"",
		"prepare_zstd_corpus || return 1",
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh missing standalone zstd corpus step %q", required)
		}
	}
	if strings.Contains(text, "share/ecs/corpus/ecs-silesia-v1.corpus") {
		t.Fatal("run.sh must not assume that the corpus is inside an ecs-tools archive")
	}
}

func TestRunScriptKeepsRunOptionsAndFiltersSubmitOptions(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	// These are ecs run flags, not wrapper flags: normal invocations and submit
	// invocations both pass the filtered positional parameters through intact.
	for _, option := range []string{
		"--profile", "--only", "--skip", "--config", "--exposure",
		"--format", "--output", "--name",
	} {
		if !strings.Contains(text, option) {
			t.Fatalf("run.sh no longer documents or handles run option %q", option)
		}
	}
	for _, option := range []string{
		"      --submit)",
		"      --provider)",
		"      --region)",
		"      --output)",
	} {
		if !strings.Contains(text, option) {
			t.Fatalf("run.sh submit filter missing %q", option)
		}
	}
	if !strings.Contains(text, `"${WORK}/ecs" "$@" --format json --output "$SUBMIT_REPORT_DIR"`) {
		t.Fatal("submit mode must pass filtered run arguments to ecs")
	}
}

func TestRunScriptOoklaPreparationUsesTemporarySource(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		"OOKLA_KEY_FINGERPRINT",
		"prepare_ookla_apt",
		"prepare_ookla_rpm",
		"install_ookla",
		"TEMP_TOOL_CACHE",
		"dpkg-deb --extract",
		// RPM 路径没有安全的临时解包器，必然以跳过收尾，因此不再生成
		// .repo 文件；apt 路径的签名保证由 signed-by= 表达。
		"signed-by=",
		"OOKLA_KEY_FINGERPRINT",
		"ECS_AUTO_DEPS=0",
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh Ookla preparation is missing %q", required)
		}
	}
	if strings.Contains(text, "Ookla is never installed automatically") || strings.Contains(text, "Ookla 不会自动安装") {
		t.Fatal("run.sh still claims that the explicit Ookla path never installs the client")
	}
	// Profile membership is supplied by the downloaded descriptor manifest;
	// the wrapper must not carry a second module registry.
	for _, required := range []string{
		`load_module_manifest`,
		`"${WORK}/ecs" list --machine`,
		`MODULE_STANDARD_MODULES`,
		`MODULE_FULL_MODULES`,
		`manifest_tools_for`,
		`ecs-module-manifest`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh is missing descriptor manifest integration %q", required)
		}
	}
	if strings.Contains(text, "LEGACY_STANDARD_MODULES") || strings.Contains(text, "LEGACY_FULL_MODULES") {
		t.Fatal("run.sh must not carry a copied profile module registry")
	}
}

func TestRunScriptOoklaDependencyPolicy(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		`manifest_tools_for "$module"`,
		"full 或显式 --only ookla 时，speedtest 进入依赖规划。",
		`if ! tool_available "$tool"; then`,
		`[ "$tool" = speedtest ] && OOKLA_MISSING=1`,
		`ECS_AUTO_DEPS=0`,
		`https://packagecloud.io/ookla/speedtest-cli/gpgkey`,
		`C525F88FCF3A7E56CE2CF59131EB3981E723ACAA`,
		`OOKLA_KEY_ASC="$WORK/ookla-packagecloud-key.asc"`,
		`OOKLA_KEYRING="$WORK/ookla-packagecloud-keyring.gpg"`,
		`OOKLA_APT_SOURCES="$WORK/ookla-packagecloud.list"`,
		`apt_ookla_command download speedtest`,
		`stage_temp_tool speedtest`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh missing Ookla dependency guard %q", required)
		}
	}
	if strings.Contains(text, `script.deb.sh |`) || strings.Contains(text, `script.rpm.sh |`) {
		t.Fatal("run.sh must not execute the vendor curl|sh installer")
	}
	if strings.Contains(text, "OOKLA_ACCEPTED") || strings.Contains(text, "$ACCEPT") {
		t.Fatal("run.sh must not gate Ookla on the removed consent flag")
	}
}

func TestRunScriptNeverInstallsSystemPackages(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		`WORK_ROOT="/tmp"`,
		`WORK=$(mktemp -d "$WORK_ROOT/ecs-run.XXXXXX")`,
		`TEMP_TOOL_ROOT="$WORK/root"`,
		`TEMP_TOOL_BIN="$WORK/bin"`,
		`APT_HOST_LISTS="/var/lib/apt/lists"`,
		`APT_STATE_MODE="host"`,
		`apt_temp_command download`,
		`apt_temp_command download $APT_RESOLVED_PACKAGES`,
		`dpkg-deb --extract`,
		`rm -f "$deb"`,
		`activate_temp_tool_path`,
		`Debian/Ubuntu`,
		`相关测试将跳过`,
		`trap cleanup EXIT`,
		`trap 'exit 130' INT TERM HUP`,
		`if [ "$KEEP" = "1" ]; then`,
		`rm -rf "$WORK"`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh is missing temporary dependency isolation guard %q", required)
		}
	}
	for _, forbidden := range []string{
		`apt-get install`,
		`apt-get purge`,
		`apt-get remove`,
		`as_root`,
		`package_state`,
		`packages.before`,
		`packages.after-install`,
		`CLEANUP_FAILED`,
		`CLEANUP_DONE`,
		`cleanup_packages`,
	} {
		if strings.Contains(text, forbidden) {
			t.Fatalf("run.sh must not use host package installation/cleanup path %q", forbidden)
		}
	}
}

func TestRunScriptStagesPrivateMultiarchLibraries(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		`append_temp_library_path`,
		`temp_library_dir_has_shared_objects`,
		`for temp_private_lib_dir in "$temp_lib_part"/*`,
		`append_temp_library_path "$temp_private_lib_dir"`,
		`libceph-common.so.2`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh is missing private multiarch library support %q", required)
		}
	}
}

func TestRunScriptNextTraceOnlyDependencyPolicy(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		"ECS_TOOLS_BASE_URL",
		"TOOLS_BASE",
		"TOOLS_ASSET=\"ecs-tools_linux_${ARCH}.tar.gz\"",
		"tools_tar_extract_member",
		`tar -xzf "$tools_archive_path"`,
		"TOOLS_STAGING_BIN",
		"sha256sum",
		"shasum -a 256",
		"nexttrace-tiny",
		"nexttrace_tool_exists",
		"remove_missing_tool \"$tools_requested\"",
		`[ -f "$tools_source" ] && [ ! -L "$tools_source" ] && [ -x "$tools_source" ]`,
		`[ "$TOOLS_ACTUAL" = "$TOOLS_EXPECTED" ]`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh is missing NextTrace dependency guard %q", required)
		}
	}
	for _, forbidden := range []string{
		"prepare_nexttrace",
		"NEXTTRACE_API_URL",
		"nexttrace_linux_${ARCH}",
		"nexttrace_cleanup_partial",
		"tar --zstd",
		"zstd -q -dc",
	} {
		if strings.Contains(text, forbidden) {
			t.Fatalf("run.sh must not retain an unsupported alternate NextTrace download path %q", forbidden)
		}
	}
	if strings.Contains(text, "trace"+"route") || strings.Contains(text, "trace"+"path") {
		t.Fatal("run.sh must not mention or prepare alternate route engines")
	}
}

func TestRunScriptPrefersSystemPingAndStagesOnlyRequestedTools(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		"tool_available \"$tool\"",
		"stream_is_official",
		"Number of Threads requested",
		"Best Rate",
		"strings \"$stream_command\"",
		"ping)",
		"cp \"$tools_source\" \"$TOOLS_STAGING_BIN/$tools_requested\"",
		"mv \"$TOOLS_STAGING_BIN\" \"$TEMP_TOOL_BIN\"",
		"ECS_AUTO_DEPS=0",
		"install_ookla",
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh missing runtime fallback guard %q", required)
		}
	}
}

func TestRunScriptUsesArchiveChecksumsAndRejectsImageMagickStream(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		`EXPECTED=$(awk -v f="$ASSET"`,
		`TOOLS_EXPECTED=$(awk -v f="$TOOLS_ASSET"`,
		`[ "$ACTUAL" = "$EXPECTED" ]`,
		`[ "$TOOLS_ACTUAL" = "$TOOLS_EXPECTED" ]`,
		`stream_is_official`,
		`grep -F 'Number of Threads requested'`,
		`grep -F 'Best Rate'`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh missing concrete digest/STREAM guard %q", required)
		}
	}
	for _, forbidden := range []string{
		"manifest.json",
		"tools_manifest_field_values",
		"tools_manifest_digest_for",
		"verify_tools_binary_digest",
		"validate_tools_manifest",
		"validate_tools_archive_layout",
		"jq -e",
		"tr '{}'",
	} {
		if strings.Contains(text, forbidden) {
			t.Fatalf("run.sh must not carry a second manifest parser %q", forbidden)
		}
	}
	if strings.Contains(text, `stream --version`) {
		t.Fatal("run.sh must not execute stream --version to identify a system command")
	}
}
