package app

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func runScriptPath(t *testing.T) string {
	t.Helper()
	_, source, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(source), "..", "..", "run.sh"))
}

func TestRunScriptUsesDirectTempOutputAndTracksThisRun(t *testing.T) {
	script := runScriptPath(t)
	if output, err := exec.Command("sh", "-n", script).CombinedOutput(); err != nil {
		t.Fatalf("sh -n run.sh: %v\n%s", err, output)
	}

	contents, err := os.ReadFile(script)
	if err != nil {
		t.Fatalf("read run.sh: %v", err)
	}
	text := string(contents)
	if strings.Contains(text, `mktemp -d "${TMPDIR:-/tmp}/ecs-reports.`) {
		t.Fatal("run.sh must not create a separate default report directory")
	}
	for _, required := range []string{
		`REPORT_DIR="${TMPDIR:-/tmp}"`,
		`comm -13 "$REPORT_BEFORE" "$REPORT_AFTER"`,
		`--output "$REPORT_DIR" --name "$REPORT_NAME"`,
		`no report generated by this run`,
		`run.sh --submit`,
		`Provider and region are auto-detected from safe local report metadata when available; --provider/--region override them, otherwise they remain blank.`,
		`有安全的本机报告元数据时会自动识别云厂商和地区；--provider/--region 可显式覆盖，无法识别时留空。`,
		`SUBMIT_PROVIDER`,
		`SUBMIT_REGION`,
		`SUBMIT_REPORT_DIR="$WORK/report"`,
		`--format json --output "$SUBMIT_REPORT_DIR"`,
		`submit --input "$SUBMIT_REPORT" --output "$SUBMIT_OUTPUT"`,
		`reject_submit_value`,
		`--provider 不能重复`,
		`--region 不能重复`,
		`--output 不能重复`,
		`ECS_PLAN_FILE=`,
		`submit --help >/dev/null 2>&1`,
		`--reveal is not allowed in submit mode`,
		`validate_submit_parent`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh missing report-output guard %q", required)
		}
	}
	if strings.Contains(text, `"${WORK}/ecs" "$@" --submit`) {
		t.Fatal("run.sh must strip --submit before invoking ecs run")
	}
	if strings.Contains(text, `--submit --profile full --yes --provider vultr --region jp-tokyo`) {
		t.Fatal("run.sh canonical submit example must not require provider or region")
	}
	reportPathsStart := strings.Index(text, "\nreport_paths() {")
	if reportPathsStart < 0 {
		t.Fatal("run.sh report_paths function is missing")
	}
	reportPathsEnd := strings.Index(text[reportPathsStart:], "\n}\n\n# 不使用 exec")
	if reportPathsEnd < 0 {
		t.Fatal("run.sh report_paths function is incomplete")
	}
	if strings.Contains(text[reportPathsStart:reportPathsStart+reportPathsEnd], `"$REPORT_DIR"/*.json`) {
		t.Fatal("run.sh must not select an arbitrary JSON from the report directory")
	}
}

func TestRunScriptKeepsRunOptionsAndFiltersSubmitOptions(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	// These are ecs run flags, not wrapper flags: normal invocations and submit
	// invocations both pass the filtered positional parameters through intact.
	for _, option := range []string{
		"--profile", "--only", "--skip", "--config", "--exposure",
		"--format", "--output", "--name",
	} {
		if !strings.Contains(text, option) {
			t.Fatalf("run.sh no longer documents or handles run option %q", option)
		}
	}
	for _, option := range []string{
		"      --submit)",
		"      --provider)",
		"      --region)",
		"      --output)",
	} {
		if !strings.Contains(text, option) {
			t.Fatalf("run.sh submit filter missing %q", option)
		}
	}
	if !strings.Contains(text, `"${WORK}/ecs" "$@" --format json --output "$SUBMIT_REPORT_DIR"`) {
		t.Fatal("submit mode must pass filtered run arguments to ecs")
	}
}

func TestRunScriptOoklaPreparationUsesTemporarySource(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		"OOKLA_KEY_FINGERPRINT",
		"prepare_ookla_apt",
		"prepare_ookla_rpm",
		"install_ookla",
		"packages.before",
		"packages.after-install",
		"gpgcheck=1",
		"signed-by=",
		"ECS_AUTO_DEPS=0",
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh Ookla preparation is missing %q", required)
		}
	}
	if strings.Contains(text, "Ookla is never installed automatically") || strings.Contains(text, "Ookla 不会自动安装") {
		t.Fatal("run.sh still claims that the explicit Ookla path never installs the client")
	}
	// Full includes Ookla directly; standard remains the ordinary 16-module set.
	fullProfile := `full) base_modules="system,network,bgp,cpu,memory,disk,dns,latency,speed,ports,nat,blacklist,apps,cnspeed,ookla,media,route,backtrace"`
	if !strings.Contains(text, fullProfile) {
		t.Fatal("run.sh full profile unexpectedly changed its default module set")
	}
	standardProfile := `standard) base_modules="system,network,bgp,cpu,memory,disk,dns,latency,speed,ports,nat,blacklist,apps,media,route,backtrace"`
	if !strings.Contains(text, standardProfile) {
		t.Fatal("run.sh standard profile unexpectedly changed its default module set")
	}
}

func TestRunScriptOoklaDependencyPolicy(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	for _, required := range []string{
		`tool_exists speedtest || add_missing_tool speedtest`,
		`speedtest) OOKLA_MISSING=1`,
		`ECS_AUTO_DEPS=0`,
		`https://packagecloud.io/ookla/speedtest-cli/gpgkey`,
		`C525F88FCF3A7E56CE2CF59131EB3981E723ACAA`,
		`OOKLA_KEY_ASC="$WORK/ookla-packagecloud-key.asc"`,
		`OOKLA_KEYRING="$WORK/ookla-packagecloud-keyring.gpg"`,
		`OOKLA_APT_SOURCES="$WORK/ookla-packagecloud.list"`,
		`OOKLA_RPM_REPO="$WORK/ookla-packagecloud.repo"`,
		`packages.before`,
		`packages.after`,
		`comm -13 "$BEFORE_PACKAGES" "$AFTER_PACKAGES"`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh missing Ookla dependency guard %q", required)
		}
	}
	if strings.Contains(text, `script.deb.sh |`) || strings.Contains(text, `script.rpm.sh |`) {
		t.Fatal("run.sh must not execute the vendor curl|sh installer")
	}
	if strings.Contains(text, "OOKLA_ACCEPTED") || strings.Contains(text, "$ACCEPT") {
		t.Fatal("run.sh must not gate Ookla on the removed consent flag")
	}
}
