package app

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func runScriptPath(t *testing.T) string {
	t.Helper()
	_, source, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(source), "..", "..", "run.sh"))
}

func TestRunScriptUsesDirectTempOutputAndTracksThisRun(t *testing.T) {
	script := runScriptPath(t)
	if output, err := exec.Command("sh", "-n", script).CombinedOutput(); err != nil {
		t.Fatalf("sh -n run.sh: %v\n%s", err, output)
	}

	contents, err := os.ReadFile(script)
	if err != nil {
		t.Fatalf("read run.sh: %v", err)
	}
	text := string(contents)
	if strings.Contains(text, `mktemp -d "${TMPDIR:-/tmp}/ecs-reports.`) {
		t.Fatal("run.sh must not create a separate default report directory")
	}
	for _, required := range []string{
		`REPORT_DIR="${TMPDIR:-/tmp}"`,
		`comm -13 "$REPORT_BEFORE" "$REPORT_AFTER"`,
		`--output "$REPORT_DIR" --name "$REPORT_NAME"`,
		`no report generated by this run`,
		`run.sh --submit`,
		`SUBMIT_PROVIDER`,
		`SUBMIT_REGION`,
		`SUBMIT_REPORT_DIR="$WORK/report"`,
		`--format json --output "$SUBMIT_REPORT_DIR"`,
		`submit --input "$SUBMIT_REPORT" --output "$SUBMIT_OUTPUT"`,
		`reject_submit_value`,
		`--provider 不能重复`,
		`--region 不能重复`,
		`--output 不能重复`,
		`ECS_PLAN_FILE=`,
		`submit --help >/dev/null 2>&1`,
		`--reveal is not allowed in submit mode`,
		`validate_submit_parent`,
	} {
		if !strings.Contains(text, required) {
			t.Fatalf("run.sh missing report-output guard %q", required)
		}
	}
	if strings.Contains(text, `"${WORK}/ecs" "$@" --submit`) {
		t.Fatal("run.sh must strip --submit before invoking ecs run")
	}
	reportPathsStart := strings.Index(text, "\nreport_paths() {")
	if reportPathsStart < 0 {
		t.Fatal("run.sh report_paths function is missing")
	}
	reportPathsEnd := strings.Index(text[reportPathsStart:], "\n}\n\n# 不使用 exec")
	if reportPathsEnd < 0 {
		t.Fatal("run.sh report_paths function is incomplete")
	}
	if strings.Contains(text[reportPathsStart:reportPathsStart+reportPathsEnd], `"$REPORT_DIR"/*.json`) {
		t.Fatal("run.sh must not select an arbitrary JSON from the report directory")
	}
}

func TestRunScriptKeepsRunOptionsAndFiltersSubmitOptions(t *testing.T) {
	contents, err := os.ReadFile(runScriptPath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(contents)
	// These are ecs run flags, not wrapper flags: normal invocations and submit
	// invocations both pass the filtered positional parameters through intact.
	for _, option := range []string{
		"--profile", "--only", "--skip", "--config", "--exposure", "--accept",
		"--format", "--output", "--name",
	} {
		if !strings.Contains(text, option) {
			t.Fatalf("run.sh no longer documents or handles run option %q", option)
		}
	}
	for _, option := range []string{
		"      --submit)",
		"      --provider)",
		"      --region)",
		"      --output)",
	} {
		if !strings.Contains(text, option) {
			t.Fatalf("run.sh submit filter missing %q", option)
		}
	}
	if !strings.Contains(text, `"${WORK}/ecs" "$@" --format json --output "$SUBMIT_REPORT_DIR"`) {
		t.Fatal("submit mode must pass filtered run arguments to ecs")
	}
}
