#!/usr/bin/env bash
# FreeBSD GNU/OpenMP build of NPB 3.4.4 EP + FT Class A (Stage 5).
#
# 唯一来源是 NASA 官方分发渠道，URL 与 SHA256 已通过代理下载两次交叉验证。
# 禁止修改 NPB source：config/make.def 按 NPB 自带 config/make.def.template
# 的官方结构生成（README.install 认可的配置机制），npbparams.h 由包内
# sys/setparams 在宿主机上生成（sys/Makefile 用 UCC=宿主 gcc 编译并运行
# setparams），两者都只是生成配置文件，不动任何源文件。

ECS_NPB_VERSION=3.4.4
ECS_NPB_URL="https://www.nas.nasa.gov/assets/npb/NPB3.4.4.tar.gz"
ECS_NPB_SHA256="1ae219398e02a0a79ad51b7460fcffbf7b5df83a69d5d3d3a9dc2d8acf523549"
ECS_NPB_CLASS=A
ECS_NPB_RAND=randi8
ECS_NPB_FFLAGS="-O3 -fopenmp"
ECS_NPB_FLINKFLAGS="-O3 -fopenmp -static"

# ecs_freebsd_gnu_npb_download OUTPUT 下载并校验官方 NPB 3.4.4 tarball。
ecs_freebsd_gnu_npb_download() {
  local output=$1 attempt actual
  mkdir -p "$(dirname "$output")"

  for attempt in 1 2 3; do
    if curl -fsSL --retry 4 --retry-delay 2 --connect-timeout 30 \
      "$ECS_NPB_URL" -o "$output"; then
      actual=$(sha256sum "$output" | awk '{print $1}')
      if [[ "$actual" == "$ECS_NPB_SHA256" ]]; then
        return 0
      fi
      echo "npb: SHA-256 mismatch on attempt $attempt/3: expected $ECS_NPB_SHA256, got $actual" >&2
    else
      echo "npb: download failed on attempt $attempt/3" >&2
    fi
    rm -f -- "$output"
  done

  return 1
}

# ecs_freebsd_gnu_npb_write_make_def MAKEDEF WRAPBIN
#
# 与 config/make.def.template 同构：Fortran 基准（EP/FT）与 common/wtime.c
# 用 wrapper（Stage 4 SDK target 编译器 + FreeBSD sysroot）；setparams 用
# UCC=宿主 gcc。-static 只落在链接旗标上。
ecs_freebsd_gnu_npb_write_make_def() {
  local make_def=$1 wrap_bin=$2
  cat >"$make_def" <<EOF
#---------------------------------------------------------------------------
# SITE- AND/OR PLATFORM-SPECIFIC DEFINITIONS.
#
# Generated by scripts/build_tools_freebsd_gnu.sh following the structure of
# config/make.def.template (the official configuration mechanism documented
# in README.install). npbparams.h is generated by the bundled sys/setparams
# run on the build host. NPB sources themselves are never modified.
#---------------------------------------------------------------------------

#---------------------------------------------------------------------------
# Parallel Fortran (EP, FT): Stage 4 GNU SDK target compiler + FreeBSD sysroot.
#---------------------------------------------------------------------------
FC = ${wrap_bin}/gfortran
FLINK = \$(FC)
F_LIB  =
F_INC =
FFLAGS = ${ECS_NPB_FFLAGS}
FLINKFLAGS = ${ECS_NPB_FLINKFLAGS}

#---------------------------------------------------------------------------
# Parallel C: only common/wtime.c is compiled here (linked into the Fortran
# binaries), so CC must be the target compiler as well.
#---------------------------------------------------------------------------
CC = ${wrap_bin}/gcc
CLINK = \$(CC)
C_LIB  =
C_INC =
CFLAGS = ${ECS_NPB_FFLAGS}
CLINKFLAGS = ${ECS_NPB_FLINKFLAGS}

#---------------------------------------------------------------------------
# Utilities C: setparams runs on the Linux build host and only generates
# config files; it must be compiled with the host compiler, never the target.
#---------------------------------------------------------------------------
UCC	= gcc

BINDIR	= ../bin

RAND   = ${ECS_NPB_RAND}
WTIME  = wtime.c
EOF
}

# ecs_freebsd_gnu_build_npb WORK STAGE WRAPBIN FILE_MACHINE
#
# 只构建 EP 与 FT Class A（Fortran 版）；产物为 static FreeBSD ELF。
ecs_freebsd_gnu_build_npb() {
  local work=$1 stage=$2 wrap_bin=$3 file_machine=$4
  local tarball="$work/src-npb.tar.gz" srcroot="$work/src-npb"
  local src="$srcroot/NPB${ECS_NPB_VERSION}/NPB${ECS_NPB_VERSION%.*}-OMP"

  echo "freebsd-gnu-tools: downloading NPB $ECS_NPB_VERSION" >&2
  ecs_freebsd_gnu_npb_download "$tarball" ||
    ecs_freebsd_gnu_die "could not download official NPB source"
  mkdir -p "$srcroot"
  tar -xzf "$tarball" -C "$srcroot"
  [[ -d "$src" ]] || ecs_freebsd_gnu_die "unexpected NPB archive layout: $src missing"

  ecs_freebsd_gnu_npb_write_make_def "$src/config/make.def" "$wrap_bin"

  # NPB 的 make 体系不能并行：config target 与 npbparams.h 规则都会调用
  # sys/setparams，而 setparams 用 fopen("w") 原地写 npbparams.h。基准编译
  # 只需数秒，串行 make 是官方用法，也消除并发写同一文件的风险。
  (
    cd "$src/EP" && make CLASS="$ECS_NPB_CLASS"
  )
  cp "$src/bin/ep.$ECS_NPB_CLASS.x" "$stage/bin/npb-ep"
  ecs_freebsd_gnu_assert_static_freebsd_elf "$stage/bin/npb-ep" "$file_machine"
  ecs_freebsd_gnu_assert_libgomp "$stage/bin/npb-ep"

  (
    cd "$src/FT" && make CLASS="$ECS_NPB_CLASS"
  )
  cp "$src/bin/ft.$ECS_NPB_CLASS.x" "$stage/bin/npb-ft"
  ecs_freebsd_gnu_assert_static_freebsd_elf "$stage/bin/npb-ft" "$file_machine"
  ecs_freebsd_gnu_assert_libgomp "$stage/bin/npb-ft"

  echo "NPB $ECS_NPB_VERSION (NAS Parallel Benchmarks), NASA Ames Research Center." \
    >"$stage/LICENSES/npb-ep.LICENSE"
  echo "License terms: see the official distribution at $ECS_NPB_URL." \
    >>"$stage/LICENSES/npb-ep.LICENSE"
  cp "$stage/LICENSES/npb-ep.LICENSE" "$stage/LICENSES/npb-ft.LICENSE"
}
